apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coffeeshop-ui
  title: CoffeShop Interface
  description: |
    This project is the interface for the Mad Cat coffeeshop ui build in react.
  annotations:
    backstage.io/kubernetes-id: 'coffeeshop-ui'
    backstage.io/kubernetes-namespace: 'coffeeshop'
    github.com/project-slug: froberge/coffeeshop-ui
    backstage.io/techdocs-ref: url:https://github.com/froberge/coffeeshop-ui
    sonarqube.org/project-key: coffeeshop-ui
    lighthouse.com/website-url: https://coffeeshop-ui-coffeeshop.apps.home.myocp.net

  tags:
    - ui
    - reactjs
    - lighthouse

  links:
    - url: https://devspaces${{values.cluster}}/#https://github.com/roberge/coffeeshop-ui?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://github.com/roberge/coffeeshop-ui?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: website
  system: janus-idp
  owner: janus-authors
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:obc
    - resource:keycloak
    - resource:github